// ═══════════════════════════════════════════════════════════════════════════
// Mock Data — YouTrack API Response Format
// Every object matches the exact structure returned by YouTrack REST API
// ═══════════════════════════════════════════════════════════════════════════

import { PROJECT } from "../config/fields.js";

// ── Team Members (as YouTrack User entities) ─────────────────────────────
export const MOCK_USERS = [
  { id: "1-1", login: "alex.kuznetsov", fullName: "Алексей Кузнецов", name: "Алексей Кузнецов", $type: "User" },
  { id: "1-2", login: "maria.sokolova", fullName: "Мария Соколова", name: "Мария Соколова", $type: "User" },
  { id: "1-3", login: "dmitry.volkov", fullName: "Дмитрий Волков", name: "Дмитрий Волков", $type: "User" },
  { id: "1-4", login: "elena.petrova", fullName: "Елена Петрова", name: "Елена Петрова", $type: "User" },
  { id: "1-5", login: "ivan.novikov", fullName: "Иван Новиков", name: "Иван Новиков", $type: "User" },
  { id: "1-6", login: "olga.nikitina", fullName: "Ольга Никитина", name: "Ольга Никитина", $type: "User" },
  { id: "1-7", login: "igor.tarasov", fullName: "Игорь Тарасов", name: "Игорь Тарасов", $type: "User" },
  { id: "1-8", login: "anna.fedorova", fullName: "Анна Фёдорова", name: "Анна Фёдорова", $type: "User" },
  { id: "1-9", login: "sergey.morozov", fullName: "Сергей Морозов", name: "Сергей Морозов", $type: "User" },
  { id: "1-10", login: "natalia.kozlova", fullName: "Наталья Козлова", name: "Наталья Козлова", $type: "User" },
];

// ── Team Capacity Config (app-level, not from YouTrack) ──────────────────
export const MOCK_TEAM_CAPACITY = [
  { login: "alex.kuznetsov",  role: "backend",  capacity: 20, tolerance: 2 },
  { login: "maria.sokolova",  role: "backend",  capacity: 18, tolerance: 2 },
  { login: "dmitry.volkov",   role: "frontend", capacity: 20, tolerance: 2 },
  { login: "elena.petrova",   role: "frontend", capacity: 16, tolerance: 2 },
  { login: "ivan.novikov",    role: "design",   capacity: 12, tolerance: 1 },
  { login: "olga.nikitina",   role: "qa",       capacity: 22, tolerance: 2 },
  { login: "igor.tarasov",    role: "qa",       capacity: 20, tolerance: 2 },
  { login: "anna.fedorova",   role: "manager",  capacity: 14, tolerance: 1 },
  { login: "sergey.morozov",  role: "backend",  capacity: 20, tolerance: 2 },
  { login: "natalia.kozlova", role: "qa",       capacity: 18, tolerance: 2 },
];

// ── Sprints (as YouTrack Sprint entities) ────────────────────────────────
export const MOCK_SPRINTS = [
  {
    id: "109-22",
    name: "Sprint 22",
    start: 1706745600000, // 2024-02-01
    finish: 1707955200000, // 2024-02-15
    archived: true,
    isDefault: false,
    unresolvedIssuesCount: 0,
    $type: "Sprint",
  },
  {
    id: "109-23",
    name: "Sprint 23",
    start: 1707955200000,
    finish: 1709164800000,
    archived: true,
    isDefault: false,
    unresolvedIssuesCount: 0,
    $type: "Sprint",
  },
  {
    id: "109-24",
    name: "Sprint 24",
    start: 1709164800000,
    finish: 1710374400000,
    archived: true,
    isDefault: false,
    unresolvedIssuesCount: 0,
    $type: "Sprint",
  },
  {
    id: "109-25",
    name: "Sprint 25",
    start: 1710374400000,
    finish: 1711584000000,
    archived: false,
    isDefault: true,
    unresolvedIssuesCount: 5,
    $type: "Sprint",
  },
  {
    id: "109-26",
    name: "Sprint 26",
    start: 1711584000000,
    finish: 1712793600000,
    archived: false,
    isDefault: false,
    unresolvedIssuesCount: 0,
    $type: "Sprint",
  },
];

// ── Helper: build a custom field in YouTrack response format ─────────────

function stateField(name, value, isResolved = false) {
  return {
    name,
    $type: "StateIssueCustomField",
    value: value
      ? { name: value, isResolved, $type: "StateBundleElement" }
      : null,
  };
}

function enumField(name, value) {
  return {
    name,
    $type: "SingleEnumIssueCustomField",
    value: value ? { name: value, $type: "EnumBundleElement" } : null,
  };
}

function multiVersionField(name, values) {
  return {
    name,
    $type: "MultiVersionIssueCustomField",
    value: values.map((v) => {
      const sprint = MOCK_SPRINTS.find((s) => s.name === v);
      return {
        id: sprint?.id || "109-0",
        name: v,
        $type: "VersionBundleElement",
      };
    }),
  };
}

function userField(name, login) {
  const user = MOCK_USERS.find((u) => u.login === login);
  return {
    name,
    $type: "SingleUserIssueCustomField",
    value: user || null,
  };
}

function intField(name, value) {
  return {
    name,
    $type: "SimpleIssueCustomField",
    value: value ?? null,
  };
}

function floatField(name, value) {
  return {
    name,
    $type: "SimpleIssueCustomField",
    value: value ?? null,
  };
}

// ── Mock Issues (Backlog + already in Sprint 25) ─────────────────────────

export const MOCK_ISSUES = [
  // ── Backlog issues (not in any sprint) ──────────────────────────────────
  {
    id: "2-1001", idReadable: "ED-101", $type: "Issue",
    summary: "Интеграция платёжного шлюза Stripe для новых рынков",
    created: 1709000000000, updated: 1710000000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Critical"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "alex.kuznetsov"),
      userField("QA", "olga.nikitina"),
      enumField("QA Priority", "1 Critical"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", 8),
      intField("Frontend Effort", null),
      intField("QA Effort", 5),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 9.2),
      intField("Business Value", 34),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1002", idReadable: "ED-102", $type: "Issue",
    summary: "Редизайн карточки отеля — мобильная версия",
    created: 1709100000000, updated: 1710100000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "dmitry.volkov"),
      userField("QA", "olga.nikitina"),
      enumField("QA Priority", "2 High"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", null),
      intField("Frontend Effort", 5),
      intField("QA Effort", 3),
      intField("Design Effort", 3),
      intField("Manager effort", null),
      floatField("Total Priority", 7.8),
      intField("Business Value", 21),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1003", idReadable: "ED-103", $type: "Issue",
    summary: "API авиабилетов: кеширование ответов партнёра",
    created: 1709200000000, updated: 1710200000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "maria.sokolova"),
      userField("QA", "igor.tarasov"),
      enumField("QA Priority", "2 High"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", 5),
      intField("Frontend Effort", null),
      intField("QA Effort", 3),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 7.5),
      intField("Business Value", 18),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1004", idReadable: "ED-104", $type: "Issue",
    summary: "Расширенные фильтры поиска туров",
    created: 1709300000000, updated: 1710300000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "elena.petrova"),
      userField("QA", "igor.tarasov"),
      enumField("QA Priority", "3 Medium"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", null),
      intField("Frontend Effort", 8),
      intField("QA Effort", 5),
      intField("Design Effort", 2),
      intField("Manager effort", null),
      floatField("Total Priority", 5.4),
      intField("Business Value", 13),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1005", idReadable: "ED-105", $type: "Issue",
    summary: "Подготовка квартального отчёта для партнёров",
    created: 1709400000000, updated: 1710400000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "anna.fedorova"),
      userField("QA", null),
      enumField("QA Priority", "5 No QA"),
      enumField("EXT Category", "Support"),
      intField("Backend Effort", null),
      intField("Frontend Effort", null),
      intField("QA Effort", null),
      intField("Design Effort", null),
      intField("Manager effort", 4),
      floatField("Total Priority", 5.0),
      intField("Business Value", 10),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1006", idReadable: "ED-106", $type: "Issue",
    summary: "Миграция БД бронирований на новый кластер",
    created: 1709500000000, updated: 1710500000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Critical"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "alex.kuznetsov"),
      userField("QA", "natalia.kozlova"),
      enumField("QA Priority", "1 Critical"),
      enumField("EXT Category", "Infrastructure"),
      intField("Backend Effort", 13),
      intField("Frontend Effort", null),
      intField("QA Effort", 5),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 8.9),
      intField("Business Value", 29),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1007", idReadable: "ED-107", $type: "Issue",
    summary: "Мобильная версия чекаута — адаптивная вёрстка",
    created: 1709600000000, updated: 1710600000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "dmitry.volkov"),
      userField("QA", "olga.nikitina"),
      enumField("QA Priority", "2 High"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", null),
      intField("Frontend Effort", 8),
      intField("QA Effort", 3),
      intField("Design Effort", 2),
      intField("Manager effort", null),
      floatField("Total Priority", 7.1),
      intField("Business Value", 20),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1008", idReadable: "ED-108", $type: "Issue",
    summary: "Логирование ошибок через Sentry — расширение покрытия",
    created: 1709700000000, updated: 1710700000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Minor"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "maria.sokolova"),
      userField("QA", "olga.nikitina"),
      enumField("QA Priority", "4 Low"),
      enumField("EXT Category", "Infrastructure"),
      intField("Backend Effort", 3),
      intField("Frontend Effort", null),
      intField("QA Effort", 2),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 2.1),
      intField("Business Value", 5),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1009", idReadable: "ED-109", $type: "Issue",
    summary: "Координация интеграции с авиа-партнёром SmartWings",
    created: 1709800000000, updated: 1710800000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "anna.fedorova"),
      userField("QA", null),
      enumField("QA Priority", "5 No QA"),
      enumField("EXT Category", "Support"),
      intField("Backend Effort", null),
      intField("Frontend Effort", null),
      intField("QA Effort", null),
      intField("Design Effort", null),
      intField("Manager effort", 6),
      floatField("Total Priority", 6.3),
      intField("Business Value", 15),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1010", idReadable: "ED-110", $type: "Issue",
    summary: "Push-уведомления о статусе бронирования",
    created: 1709900000000, updated: 1710900000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "sergey.morozov"),
      userField("QA", "natalia.kozlova"),
      enumField("QA Priority", "3 Medium"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", 5),
      intField("Frontend Effort", 3),
      intField("QA Effort", 3),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 4.8),
      intField("Business Value", 12),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1011", idReadable: "ED-111", $type: "Issue",
    summary: "Страница программы лояльности клиентов",
    created: 1710000000000, updated: 1711000000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "elena.petrova"),
      userField("QA", "olga.nikitina"),
      enumField("QA Priority", "3 Medium"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", null),
      intField("Frontend Effort", 6),
      intField("QA Effort", 4),
      intField("Design Effort", 3),
      intField("Manager effort", null),
      floatField("Total Priority", 4.5),
      intField("Business Value", 14),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1012", idReadable: "ED-112", $type: "Issue",
    summary: "Оптимизация SQL-запросов к базе бронирований",
    created: 1710100000000, updated: 1711100000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Minor"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "maria.sokolova"),
      userField("QA", "igor.tarasov"),
      enumField("QA Priority", "4 Low"),
      enumField("EXT Category", "Infrastructure"),
      intField("Backend Effort", 5),
      intField("Frontend Effort", null),
      intField("QA Effort", 2),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 2.8),
      intField("Business Value", 8),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1013", idReadable: "ED-113", $type: "Issue",
    summary: "Онбординг нового партнёра — TUI Hotels",
    created: 1710200000000, updated: 1711200000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "anna.fedorova"),
      userField("QA", null),
      enumField("QA Priority", "5 No QA"),
      enumField("EXT Category", "Support"),
      intField("Backend Effort", null),
      intField("Frontend Effort", null),
      intField("QA Effort", null),
      intField("Design Effort", null),
      intField("Manager effort", 3),
      floatField("Total Priority", 3.7),
      intField("Business Value", 9),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1014", idReadable: "ED-114", $type: "Issue",
    summary: "SSO авторизация через Google OAuth для B2B-кабинета",
    created: 1710300000000, updated: 1711300000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "sergey.morozov"),
      userField("QA", "igor.tarasov"),
      enumField("QA Priority", "2 High"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", 5),
      intField("Frontend Effort", 3),
      intField("QA Effort", 3),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 6.7),
      intField("Business Value", 16),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1015", idReadable: "ED-115", $type: "Issue",
    summary: "Виджет сравнения цен на странице поиска",
    created: 1710400000000, updated: 1711400000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Feature"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "dmitry.volkov"),
      userField("QA", "natalia.kozlova"),
      enumField("QA Priority", "3 Medium"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", null),
      intField("Frontend Effort", 5),
      intField("QA Effort", 3),
      intField("Design Effort", 2),
      intField("Manager effort", null),
      floatField("Total Priority", 4.2),
      intField("Business Value", 11),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1016", idReadable: "ED-116", $type: "Issue",
    summary: "Дизайн-система: обновление UI-kit до v3",
    created: 1710500000000, updated: 1711500000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "ivan.novikov"),
      userField("QA", null),
      enumField("QA Priority", "5 No QA"),
      enumField("EXT Category", "Design"),
      intField("Backend Effort", null),
      intField("Frontend Effort", null),
      intField("QA Effort", null),
      intField("Design Effort", 8),
      intField("Manager effort", null),
      floatField("Total Priority", 4.0),
      intField("Business Value", 10),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },
  {
    id: "2-1017", idReadable: "ED-117", $type: "Issue",
    summary: "Прототипы экранов бронирования трансфера",
    created: 1710600000000, updated: 1711600000000, resolved: null,
    customFields: [
      stateField("State", "Backlog"),
      enumField("Type", "Task"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", []),
      userField("Assignee", "ivan.novikov"),
      userField("QA", null),
      enumField("QA Priority", "5 No QA"),
      enumField("EXT Category", "Design"),
      intField("Backend Effort", null),
      intField("Frontend Effort", null),
      intField("QA Effort", null),
      intField("Design Effort", 5),
      intField("Manager effort", null),
      floatField("Total Priority", 5.6),
      intField("Business Value", 13),
      intField("• Reopen counter", 0),
      intField("% Done", 0),
    ],
  },

  // ── Issues already in Sprint 25 ─────────────────────────────────────────
  {
    id: "2-1050", idReadable: "ED-050", $type: "Issue",
    summary: "Рефакторинг сервиса поиска — разделение на микросервисы",
    created: 1708000000000, updated: 1710500000000, resolved: null,
    customFields: [
      stateField("State", "In Progress"),
      enumField("Type", "Task"),
      enumField("Priority", "Critical"),
      multiVersionField("EXT Sprint", ["Sprint 25"]),
      userField("Assignee", "alex.kuznetsov"),
      userField("QA", "igor.tarasov"),
      enumField("QA Priority", "1 Critical"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", 8),
      intField("Frontend Effort", null),
      intField("QA Effort", 5),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 8.5),
      intField("Business Value", 25),
      intField("• Reopen counter", 1),
      intField("% Done", 40),
    ],
  },
  {
    id: "2-1051", idReadable: "ED-051", $type: "Issue",
    summary: "Форма обратной связи — фронтенд + валидация",
    created: 1708100000000, updated: 1710600000000, resolved: null,
    customFields: [
      stateField("State", "In Progress"),
      enumField("Type", "Feature"),
      enumField("Priority", "Normal"),
      multiVersionField("EXT Sprint", ["Sprint 25"]),
      userField("Assignee", "elena.petrova"),
      userField("QA", "natalia.kozlova"),
      enumField("QA Priority", "3 Medium"),
      enumField("EXT Category", "Development"),
      intField("Backend Effort", null),
      intField("Frontend Effort", 5),
      intField("QA Effort", 3),
      intField("Design Effort", null),
      intField("Manager effort", null),
      floatField("Total Priority", 4.1),
      intField("Business Value", 8),
      intField("• Reopen counter", 0),
      intField("% Done", 60),
    ],
  },
  {
    id: "2-1052", idReadable: "ED-052", $type: "Issue",
    summary: "Согласование SLA с новым платёжным провайдером",
    created: 1708200000000, updated: 1710700000000, resolved: null,
    customFields: [
      stateField("State", "Open"),
      enumField("Type", "Task"),
      enumField("Priority", "Major"),
      multiVersionField("EXT Sprint", ["Sprint 25"]),
      userField("Assignee", "anna.fedorova"),
      userField("QA", null),
      enumField("QA Priority", "5 No QA"),
      enumField("EXT Category", "Support"),
      intField("Backend Effort", null),
      intField("Frontend Effort", null),
      intField("QA Effort", null),
      intField("Design Effort", null),
      intField("Manager effort", 5),
      floatField("Total Priority", 6.0),
      intField("Business Value", 14),
      intField("• Reopen counter", 0),
      intField("% Done", 10),
    ],
  },
];

// ── Historical sprint data (for metrics) ─────────────────────────────────
// Simulates what we'd compute from activity history API
export const MOCK_SPRINT_HISTORY = [
  {
    sprintId: "109-22",
    sprintName: "Sprint 22",
    planned: 14,
    completed: 11,
    reopened: 2,
    carryOver: 3,
    totalEffort: { backend: 38, frontend: 22, qa: 30, design: 4, manager: 8 },
  },
  {
    sprintId: "109-23",
    sprintName: "Sprint 23",
    planned: 12,
    completed: 10,
    reopened: 1,
    carryOver: 2,
    totalEffort: { backend: 32, frontend: 18, qa: 25, design: 6, manager: 5 },
  },
  {
    sprintId: "109-24",
    sprintName: "Sprint 24",
    planned: 15,
    completed: 12,
    reopened: 3,
    carryOver: 3,
    totalEffort: { backend: 40, frontend: 28, qa: 35, design: 8, manager: 10 },
  },
];
